### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'start_ea'

### ISSUE THREAD

**Issue by umiiii** [argp/iBoot64helper#6]
Trying to load `SecureROM for t8030si, iBoot-4479.0.0.100.4` with your loader.

Got those error:
```
/Applications/IDA Pro 7.0/ida.app/Contents/MacOS/loaders/iBoot64helper.py: Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida.app/Contents/MacOS/loaders/iBoot64helper.py", line 375, in load_file
    find_interesting(segment_start, segment_end)
  File "/Applications/IDA Pro 7.0/ida.app/Contents/MacOS/loaders/iBoot64helper.py", line 266, in find_interesting
    pk_ea = find_panic(base_ea)
  File "/Applications/IDA Pro 7.0/ida.app/Contents/MacOS/loaders/iBoot64helper.py", line 34, in find_panic
    print("\t[+] _panic = 0x%x" % (func.start_ea))
AttributeError: 'NoneType' object has no attribute 'start_ea'
```

Works well with `SecureROM for t8020si, iBoot-3865.0.0.4.6`

SecureROM can be found here: https://github.com/zzVertigo/SecureROMs

Environment:

IDA version: Version 7.0.170914, macOS Catalina

**Comment by argp** [comment]
I don't have IDA 7.0 to test.

It works fine with 7.3 and 7.4, and the SecureROM image you specified.

But try renaming "start_ea" to "startEA".
